import { AlertService } from './alert.service';
export declare class AlertController {
    private readonly alertService;
    constructor(alertService: AlertService);
    getRules(req: any): Promise<{
        description: string | null;
        metric: string;
        name: string;
        id: string;
        tenantId: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        campaignId: string | null;
        severity: import(".prisma/client").$Enums.AlertSeverity;
        alertType: import(".prisma/client").$Enums.AlertRuleType;
        operator: string;
        threshold: import("@prisma/client-runtime-utils").Decimal;
        notificationChannels: import("@prisma/client/runtime/client").JsonValue | null;
        recipients: import("@prisma/client/runtime/client").JsonValue | null;
        lastTriggeredAt: Date | null;
        triggerCount: number;
    }[]>;
    initializePresetRules(req: any): Promise<{
        description: string | null;
        metric: string;
        name: string;
        id: string;
        tenantId: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        campaignId: string | null;
        severity: import(".prisma/client").$Enums.AlertSeverity;
        alertType: import(".prisma/client").$Enums.AlertRuleType;
        operator: string;
        threshold: import("@prisma/client-runtime-utils").Decimal;
        notificationChannels: import("@prisma/client/runtime/client").JsonValue | null;
        recipients: import("@prisma/client/runtime/client").JsonValue | null;
        lastTriggeredAt: Date | null;
        triggerCount: number;
    }[]>;
    createRule(req: any, body: {
        name: string;
        metric: string;
        operator: string;
        threshold: number;
        severity?: string;
        description?: string;
    }): Promise<{
        description: string | null;
        metric: string;
        name: string;
        id: string;
        tenantId: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        campaignId: string | null;
        severity: import(".prisma/client").$Enums.AlertSeverity;
        alertType: import(".prisma/client").$Enums.AlertRuleType;
        operator: string;
        threshold: import("@prisma/client-runtime-utils").Decimal;
        notificationChannels: import("@prisma/client/runtime/client").JsonValue | null;
        recipients: import("@prisma/client/runtime/client").JsonValue | null;
        lastTriggeredAt: Date | null;
        triggerCount: number;
    }>;
    updateRule(req: any, id: string, body: any): Promise<{
        description: string | null;
        metric: string;
        name: string;
        id: string;
        tenantId: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        campaignId: string | null;
        severity: import(".prisma/client").$Enums.AlertSeverity;
        alertType: import(".prisma/client").$Enums.AlertRuleType;
        operator: string;
        threshold: import("@prisma/client-runtime-utils").Decimal;
        notificationChannels: import("@prisma/client/runtime/client").JsonValue | null;
        recipients: import("@prisma/client/runtime/client").JsonValue | null;
        lastTriggeredAt: Date | null;
        triggerCount: number;
    }>;
    toggleRule(req: any, id: string): Promise<{
        description: string | null;
        metric: string;
        name: string;
        id: string;
        tenantId: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        campaignId: string | null;
        severity: import(".prisma/client").$Enums.AlertSeverity;
        alertType: import(".prisma/client").$Enums.AlertRuleType;
        operator: string;
        threshold: import("@prisma/client-runtime-utils").Decimal;
        notificationChannels: import("@prisma/client/runtime/client").JsonValue | null;
        recipients: import("@prisma/client/runtime/client").JsonValue | null;
        lastTriggeredAt: Date | null;
        triggerCount: number;
    }>;
    deleteRule(req: any, id: string): Promise<{
        description: string | null;
        metric: string;
        name: string;
        id: string;
        tenantId: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        campaignId: string | null;
        severity: import(".prisma/client").$Enums.AlertSeverity;
        alertType: import(".prisma/client").$Enums.AlertRuleType;
        operator: string;
        threshold: import("@prisma/client-runtime-utils").Decimal;
        notificationChannels: import("@prisma/client/runtime/client").JsonValue | null;
        recipients: import("@prisma/client/runtime/client").JsonValue | null;
        lastTriggeredAt: Date | null;
        triggerCount: number;
    }>;
    getAlerts(req: any, status?: string, severity?: string, limit?: string): Promise<({
        campaign: {
            name: string;
            id: string;
            platform: import(".prisma/client").$Enums.AdPlatform;
        };
        rule: {
            name: string;
            id: string;
        };
    } & {
        type: string;
        title: string;
        id: string;
        tenantId: string;
        createdAt: Date;
        status: import(".prisma/client").$Enums.AlertStatus;
        campaignId: string | null;
        metadata: import("@prisma/client/runtime/client").JsonValue | null;
        message: string;
        ruleId: string | null;
        severity: import(".prisma/client").$Enums.AlertSeverity;
        resolvedAt: Date | null;
    })[]>;
    getOpenAlertsCount(req: any): Promise<{
        total: number;
        critical: number;
        warning: number;
        info: number;
    }>;
    checkAlerts(req: any): Promise<any[]>;
    acknowledgeAlert(req: any, id: string): Promise<{
        type: string;
        title: string;
        id: string;
        tenantId: string;
        createdAt: Date;
        status: import(".prisma/client").$Enums.AlertStatus;
        campaignId: string | null;
        metadata: import("@prisma/client/runtime/client").JsonValue | null;
        message: string;
        ruleId: string | null;
        severity: import(".prisma/client").$Enums.AlertSeverity;
        resolvedAt: Date | null;
    }>;
    resolveAlert(req: any, id: string): Promise<{
        type: string;
        title: string;
        id: string;
        tenantId: string;
        createdAt: Date;
        status: import(".prisma/client").$Enums.AlertStatus;
        campaignId: string | null;
        metadata: import("@prisma/client/runtime/client").JsonValue | null;
        message: string;
        ruleId: string | null;
        severity: import(".prisma/client").$Enums.AlertSeverity;
        resolvedAt: Date | null;
    }>;
    resolveAllAlerts(req: any): Promise<import(".prisma/client").Prisma.BatchPayload>;
}
