import { PrismaService } from '../prisma/prisma.service';
import { NotificationService } from '../notification/notification.service';
import { Prisma, AlertSeverity, AlertStatus } from '@prisma/client';
export declare class AlertService {
    private readonly prisma;
    private readonly notificationService;
    private readonly logger;
    constructor(prisma: PrismaService, notificationService: NotificationService);
    getRules(tenantId: string): Promise<{
        description: string | null;
        metric: string;
        name: string;
        id: string;
        tenantId: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        campaignId: string | null;
        severity: import(".prisma/client").$Enums.AlertSeverity;
        alertType: import(".prisma/client").$Enums.AlertRuleType;
        operator: string;
        threshold: Prisma.Decimal;
        notificationChannels: Prisma.JsonValue | null;
        recipients: Prisma.JsonValue | null;
        lastTriggeredAt: Date | null;
        triggerCount: number;
    }[]>;
    initializePresetRules(tenantId: string): Promise<{
        description: string | null;
        metric: string;
        name: string;
        id: string;
        tenantId: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        campaignId: string | null;
        severity: import(".prisma/client").$Enums.AlertSeverity;
        alertType: import(".prisma/client").$Enums.AlertRuleType;
        operator: string;
        threshold: Prisma.Decimal;
        notificationChannels: Prisma.JsonValue | null;
        recipients: Prisma.JsonValue | null;
        lastTriggeredAt: Date | null;
        triggerCount: number;
    }[]>;
    createRule(tenantId: string, data: {
        name: string;
        metric: string;
        operator: string;
        threshold: number;
        severity?: AlertSeverity;
        description?: string;
    }): Promise<{
        description: string | null;
        metric: string;
        name: string;
        id: string;
        tenantId: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        campaignId: string | null;
        severity: import(".prisma/client").$Enums.AlertSeverity;
        alertType: import(".prisma/client").$Enums.AlertRuleType;
        operator: string;
        threshold: Prisma.Decimal;
        notificationChannels: Prisma.JsonValue | null;
        recipients: Prisma.JsonValue | null;
        lastTriggeredAt: Date | null;
        triggerCount: number;
    }>;
    updateRule(ruleId: string, tenantId: string, data: Prisma.AlertRuleUpdateInput): Promise<{
        description: string | null;
        metric: string;
        name: string;
        id: string;
        tenantId: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        campaignId: string | null;
        severity: import(".prisma/client").$Enums.AlertSeverity;
        alertType: import(".prisma/client").$Enums.AlertRuleType;
        operator: string;
        threshold: Prisma.Decimal;
        notificationChannels: Prisma.JsonValue | null;
        recipients: Prisma.JsonValue | null;
        lastTriggeredAt: Date | null;
        triggerCount: number;
    }>;
    toggleRule(ruleId: string, tenantId: string): Promise<{
        description: string | null;
        metric: string;
        name: string;
        id: string;
        tenantId: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        campaignId: string | null;
        severity: import(".prisma/client").$Enums.AlertSeverity;
        alertType: import(".prisma/client").$Enums.AlertRuleType;
        operator: string;
        threshold: Prisma.Decimal;
        notificationChannels: Prisma.JsonValue | null;
        recipients: Prisma.JsonValue | null;
        lastTriggeredAt: Date | null;
        triggerCount: number;
    }>;
    deleteRule(ruleId: string, tenantId: string): Promise<{
        description: string | null;
        metric: string;
        name: string;
        id: string;
        tenantId: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        campaignId: string | null;
        severity: import(".prisma/client").$Enums.AlertSeverity;
        alertType: import(".prisma/client").$Enums.AlertRuleType;
        operator: string;
        threshold: Prisma.Decimal;
        notificationChannels: Prisma.JsonValue | null;
        recipients: Prisma.JsonValue | null;
        lastTriggeredAt: Date | null;
        triggerCount: number;
    }>;
    getAlerts(tenantId: string, options?: {
        status?: AlertStatus;
        severity?: AlertSeverity;
        limit?: number;
    }): Promise<({
        campaign: {
            name: string;
            id: string;
            platform: import(".prisma/client").$Enums.AdPlatform;
        };
        rule: {
            name: string;
            id: string;
        };
    } & {
        type: string;
        title: string;
        id: string;
        tenantId: string;
        createdAt: Date;
        status: import(".prisma/client").$Enums.AlertStatus;
        campaignId: string | null;
        metadata: Prisma.JsonValue | null;
        message: string;
        ruleId: string | null;
        severity: import(".prisma/client").$Enums.AlertSeverity;
        resolvedAt: Date | null;
    })[]>;
    getOpenAlertsCount(tenantId: string): Promise<{
        total: number;
        critical: number;
        warning: number;
        info: number;
    }>;
    acknowledgeAlert(alertId: string, tenantId: string): Promise<{
        type: string;
        title: string;
        id: string;
        tenantId: string;
        createdAt: Date;
        status: import(".prisma/client").$Enums.AlertStatus;
        campaignId: string | null;
        metadata: Prisma.JsonValue | null;
        message: string;
        ruleId: string | null;
        severity: import(".prisma/client").$Enums.AlertSeverity;
        resolvedAt: Date | null;
    }>;
    resolveAlert(alertId: string, tenantId: string): Promise<{
        type: string;
        title: string;
        id: string;
        tenantId: string;
        createdAt: Date;
        status: import(".prisma/client").$Enums.AlertStatus;
        campaignId: string | null;
        metadata: Prisma.JsonValue | null;
        message: string;
        ruleId: string | null;
        severity: import(".prisma/client").$Enums.AlertSeverity;
        resolvedAt: Date | null;
    }>;
    resolveAllAlerts(tenantId: string): Promise<Prisma.BatchPayload>;
    checkAlerts(tenantId: string): Promise<any[]>;
    private aggregateMetrics;
    private checkRule;
    private generateAlertMessage;
}
